@startuml


actor User

component Component

cloud Cloud {
	node dbserver {
		database "DB" {
			[<u><font color=blue>App</font></u>] as APP
		}
	}
}

note left of Cloud
  This is a note
  [[http://www.google.com]]
end note


@enduml
